packages:
  - 'bundles/*'
  - 'cli'
  - 'cli/files/create-preset/js'
  - 'cli/files/create-preset/ts'
  - 'components/*'
  - 'demo/**/*'
  - 'editor'
  - 'engine'
  - 'interactions/*'
  - 'interactions/external/*'
  - 'interactions/particles/*'
  - 'move/*'
  - 'paths/*'
  - 'plugins/*'
  - 'presets/*'
  - 'shapes/*'
  - 'templates/*'
  - 'updaters/*'
  - 'utils/*'
  - 'website'
